version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev  # corrected typo here
    ports:
      - '5000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true  # Enable polling for file changes

  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "test"]  

